#!/bin/bash
#__ __ ___ ___ ___ _____ _
#\ \ /(_-</ _ `/ // / _ `/  XSM post installation script
#/_\_\/___/\_,_/\_, /\_,_/                        /xsaya
# 󰦕   サ   ガ  /___/          

sudo pacman -S --needed gnupg xclip git stow
echo "decrypting..."
gpg -d xsm-e5qu31fh28if3g7nzmjhf.gpg | xclip -selection clipboard
gpg -d xsm-e5qu31fh28if3g7nzmjhf.gpg | xclip

echo
echo "token copied to clipboard."
echo
echo -n "Proceed with installation of xsm?(y/N): "
read
[ "$REPLY" = "y" ] && echo "fetching configuration..." || exit

cd
git clone https://github.com/vsaya/dotfiles
echo "deploying configuration."
cd dotfiles
stow *
echo "configuration stowed."
cd .stow-local-ignore/
./xsm-bootstrap
